version: "3.9"

services:
  idos-api:
    build: .
    container_name: idos-api
    ports:
      - "8001:8000"   # FastAPI
    volumes:
      - ./app.py:/app/app.py
      - ./routes.py:/app/routes.py
      - ./peers.py:/app/peers.py
      - ./proxies.py:/app/proxies.py
      - playwright_data:/opt/ms-playwright
    stdin_open: true
    tty: true

volumes:
  playwright_data:
