services:
  - type: web
    name: idos-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /status
    plan: free
    region: frankfurt
    envVars:
      - key: BOOTSTRAP_PEERS
        value: "https://idos.numerlab.org"
      - key: PEERS_CACHE
        value: /app/peers_cache.json
      - key: PEER_REDISCOVER
        value: "3600"
      - key: PEER_ROUTING
        value: "1"
      - key: MAX_HOPS
        value: "1"
      - key: PEER_VERSION
        value: "1"
      - key: PEER_COMPATIBLE_VERSIONS
        value: "1"
      - key: PROXY_ENABLED
        value: "0"
      - key: PROXY_MAX_TRIES
        value: "3"
      - key: PROXY_REFRESH
        value: "3600"
